### ISSUE TITLE
We changed the structure

### ISSUE THREAD

**Issue by Sytten** [caido-community/burp2caido#1]
Hello :)

We changed the structure in the database. There is now a new `requests_metadata` table that needs to be populated and linked to the `requests` table for everything to work.

You can assume a one-to-one for this new table, the reasoning behind it is that we use a hierarchy of requests (parent/children) when you do modifications like Match&Replace or manual edits, but we share some things like the metadata.

**Comment by projectmonke** [comment]
Hi @Sytten,

Thanks for the heads-up! I'll address it this week.

**Comment by projectmonke** [comment]
Hi @Sytten,

This has now been patched. Thanks!
